apply from: 'gradle/scripts/helpers.gradle'

repositories {
    // Other repositories described by default:
    // CleanroomMC: https://maven.cleanroommc.com
    maven {
        name 'CurseMaven'
        url 'https://cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
    maven {
        name 'CleanroomCurseMaven'
        url 'https://curse.cleanroommc.com'
        content {
            includeGroup 'curse.maven'
        }
    }
    maven {
        name 'Modrinth'
        url 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }
    maven {
        name "JitPack"
        url 'https://jitpack.io'
    }
    maven {
        name 'GTCEu Maven'
        url 'https://maven.gtceu.com'
    }
    maven {
        name 'CleanroomMC Maven'
        url 'https://repo.cleanroommc.com/releases'
    }
//    maven {
//        name 'BlameJared'
//        url 'https://maven.blamejared.com/'
//    }
    mavenLocal() // Must be last for caching to work
}

dependencies {
    // Include StripLatestForgeRequirements by default for the dev env, saves everyone a hassle
    runtimeOnly 'com.cleanroommc:strip-latest-forge-requirements:1.0'
    // Include OSXNarratorBlocker by default for the dev env, for M1+ Macs
    runtimeOnly 'com.cleanroommc:osxnarratorblocker:1.0'

    // Example - Dependency descriptor:
    // 'com.google.code.gson:gson:2.8.6' << group: com.google.code.gson, name:gson, version:2.8.6
    // 'group:name:version:classifier' where classifier is optional

    // Example - Deobfuscating dependencies:
    // rfg.deobf('curse.maven:had-enough-items-557549:4543375')
    // By wrapping a dependency descriptor in rfg.deobf() method call, the dependency is queued for deobfuscation
    // When deobfuscating, RFG respects the mapping_channel + mapping_version stated in gradle.properties

    // Example - CurseMaven dependencies:
    // 'curse.maven:had-enough-items-557549:4543375' << had-enough-items = project slug, 557549 = project id, 4543375 = file id
    // Full documentation: https://cursemaven.com/

    // Example - Modrinth dependencies:
    // 'maven.modrinth:jei:4.16.1.1000' << jei = project name, 4.16.1.1000 = file version
    // Full documentation: https://docs.modrinth.com/docs/tutorials/maven/

    // Common dependency types (configuration):
    // implementation = dependency available at both compile time and runtime
    // runtimeOnly = runtime dependency
    // compileOnly = compile time dependency
    // annotationProcessor = annotation processing dependencies
    // embed = bundle dependencies into final output artifact (no relocation)

    // Transitive dependencies:
    // (Dependencies that your dependency depends on)
    // If you wish to exclude transitive dependencies in the described dependencies
    // Use a closure as such:
    // implementation ('com.google.code.gson:gson:2.8.6') {
    //     transitive = false
    // }

    implementation "com.cleanroommc:configanytime:3.0"
    implementation 'mezz:jei:4.30.2'
    implementation rfg.deobf("curse.maven:baubles-227083:2518667")
//    runtimeOnly rfg.deobf("curse.maven:baubles-ex-1096600:7609484")
    implementation 'com.github.hohserg1:HookLib:662491e893b4eec0962c37371f87024846b7f407'
    implementation('com.enderio:endercore:0.5.78') { transitive = false }
    implementation('crazypants:enderio:5.3.72') { transitive = false }
    implementation rfg.deobf("curse.maven:cofh_core-69162:2920433")
    implementation rfg.deobf("curse.maven:cofh_world-271384:2920434")
    implementation rfg.deobf("curse.maven:thermal_foundation-222880:2926428")
    implementation rfg.deobf("curse.maven:redstone_flux-270789:2920436")
    implementation rfg.deobf("curse.maven:top-addons-247111:2887479")
    runtimeOnly rfg.deobf("curse.maven:theonesmeagle-977883:7095096")

//    implementation fileTree("libs")

    runtimeOnly fileTree("dev")

}

if (propertyBool('enable_shadow')) {
    tasks.named("shadowJar").configure {
        // Exclude specific parts of deps to keep your jar clean
        // dependencies {
        //     exclude 'META-INF/maven/**'
        // }

        // Relocate specific parts of deps, so multiple shaded classes in mods will not conflict
        // relocate "mezz.jei", "shaded.mezz.jei"

        // Remove unused classes automatically. May cause issues if they are accessed by reflection
        // minimize()
    }
}